Update bootstrap3 to bootstrap4
It looks like bootstrap3[1] was only supported with version Django2 with
Django3 I discovered problems like:

```
File "/usr/local/lib/python3.8/site-packages/bootstrap3/utils.py", line 7, in <module>
  from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.8/site-packages/django/utils/__init__.py)
```

This patch moves to bootstrap4[2]

[1] https://pypi.org/project/django-bootstrap3/
[2] https://pypi.org/project/django-bootstrap4/